### ISSUE TITLE
Consider moving to DDEV org

### ISSUE THREAD

**Issue by rfay** [ddev/vscode-ddev-manager#13]
You're doing such a great job of maintaining this, I can see it has a great future. 

I think it would be easier for you in the long term, and for people to find it and understand where to put issues, if it moved to the ddev org on Github. This is really easy, and redirects work fine, and you'd remain the maintainer with the same full privileges you currently have.

Anyway, think about it!

Thanks,
-Randy

**Comment by biati-digital** [comment]
Hi Randy, the extension is coming along nicely, not sure if you have checked the [roadmap](https://github.com/users/biati-digital/projects/1), I’ve added a lot of new functionalities since the first release.

I was not aware of the DDEV org, not sure I fully understand what this means, never done it before.

One thing I wanted to clarify. While I was looking for information about the org I ended up looking the advisory group meetings and in the last meeting notes it’s says that the extension is maintained by Simon Siefke, **this is not correct**, he created [another](https://marketplace.visualstudio.com/items?itemName=SimonSiefke.ddev) DDEV extension but was last updated in 2019, just wanted to clarify this to avoid any confusion.

**Comment by rfay** [comment]
Oops! I wonder if there's a way to get rid of that old one.  The folks who were taking notes apparently just did a quick search and put the wrong thing in there.  I updated the google doc.

When I say the "ddev" org, I mean github.com/ddev. So this project would move to github.com/ddev/vscode-ddev-manager under my proposal.

**Comment by biati-digital** [comment]
If I'm not mistaken the only one that can delete the extension is the owner. I saw some time ago that you could report the extension in some Microsoft GitHub repo, and they will try to contact the developer, if he does not respond the extension is marked as "Deprecated" I'll try to investigate.

Sure, I'm ok with moving it, let me know what I've to do.

**Comment by rfay** [comment]
I just invited you as owner to github.com/ddevl - Please use the settings to transfer to ddevl, then when you've done that I'll transfer it to ddev. Github is really, really good at redirections, so on the github side this shouldn't cause any trouble, and I know you'll update the vscode store side right away.  After it moves there will be some fiddling. The fact that it's gotten a lot of publicity already makes us hope that the vscode store does a good job.

**Comment by biati-digital** [comment]
Sure, I'll update the links, as you mentioned, Github it's doing a good job with redirections, the marketplace links redirect correctly to ddev/vscode-ddev-manager

I'm working on an update so I'll update all the links 👍
